[ui]
paginate = "auto"
pager = ":builtin"
default-command = "log"
editor = "nvim"
merge-editor = "vscode"

[user]
name = "jack-mil"
email = "62065280+jack-mil@users.noreply.github.com"

[signing]
sign-all = true
backend = "ssh"
key = "~/.ssh/id_git_sign.pub"

[template-aliases]
'format_short_signature(signature)' = 'signature.name()'
'format_timestamp(timestamp)' = 'timestamp.format("%R %F")'

[colors]
name = "yellow"
