[ui]
paginate = "auto"
pager = ":builtin"
default-command = "log"
editor = "nvim"
merge-editor = "code"

[user]
name = "jack-mil"
email = "62065280+jack-mil@users.noreply.github.com"

{{#if signing_key}}
[signing]
  key = "{{signing_key}}"
  sign-all = true
  {{#if (eq (extension signing_key) "pub")}}
  backend = "ssh"
  {{/if}}
{{/if}}

[template-aliases]
'format_short_signature(signature)' = 'signature.name()'
'format_timestamp(timestamp)' = 'timestamp.format("%R %F")'

[colors]
name = "yellow"
branch = "magenta"
