[general]
  cpus      = 16
  doas      = false
  editor    = "nvim"
  language  = "en-US"
  noconfirm = false

[aur]
  build         = "/home/jackmil/.cache/aura/builds"
  cache         = "/home/jackmil/.cache/aura/cache"
  chroot        = []
  clean         = false
  clones        = "/home/jackmil/.cache/aura/packages"
  delmakedeps   = false
  diff          = true
  git           = false
  hashes        = "/home/jackmil/.cache/aura/hashes"
  hotedit       = false
  ignores       = []
  nocheck       = false
  reverse       = false
  shellcheck    = false
  skipdepcheck  = false
  warn_unknowns = true

[backups]
  automatic = true
  snapshots = "/home/jackmil/.cache/aura/snapshots"
