exclude = ["jj/config.toml"]

[formatting]
  align_comments        = true
  align_entries         = true
  array_auto_expand     = true
  column_width          = 60
  indent_entries        = true
  indent_string         = "  "
  indent_tables         = true
  reorder_arrays        = false
  reorder_inline_tables = true
  reorder_keys          = true

# [[rule]]
#   include = ["**/starship.toml"]
#   keys    = ["palettes"]

#   formatting.reorder_keys = false
