"$schema" = 'https://starship.rs/config-schema.json'

# Almost default (yellow & teal are swapped)
palette = "catppuccin_frappe"

# shorter limit for scaning filesystem
scan_timeout = 10

# wrap if gets too long
add_newline = true

format = """
[╭ ](bold subtext0)$username$hostname$shlvl\
$directory$git_branch$git_commit$git_state$git_metrics$git_status\
$fill\
$package$c$cmake$julia$kotlin$python$rust\
$env_var$custom$sudo$cmd_duration\
$line_break\
[╰](bold subtext0)$jobs$time$status$os$container$shell$character"""

# Starship modules
[character]
  error_symbol   = "[❯](bold red)"
  success_symbol = "[❯](bold peach)"
  # For use with zsh-vi-mode
  vimcmd_symbol = "[❮](bold peach)"

[directory]
  before_repo_root_style    = "bold sapphire"
  fish_style_pwd_dir_length = 4
  read_only                 = " 󰌾"
  repo_root_style           = "bold italic flamingo"
  style                     = "bold lavender"
  truncation_length         = 4
  use_os_path_sep           = false
  #   [directory.substitutions]
  # Can't be used with fish_style_path :\
  #     "Documents" = " "
  #     "Downloads" = " "
  #     "Music"     = " "
  #     "Pictures"  = " "
[shlvl]
disabled = false

[git_branch]
  format            = '[$symbol$branch(:$remote_branch)]($style) '
  style             = "bold pink"
  symbol            = " "
  truncation_length = 20

[git_status]
  style = "bold yellow"

[git_metrics]
  # too slow...
  disabled = true

[username]
  format     = '[\[](red)[$user]($style)'
  style_user = "italic yellow"

[hostname]
  format     = '[@](red)[$ssh_symbole$hostname]($style)[\]](red) '
  ssh_symbol = " "
  style      = "bold teal"

[cmake]
  symbol = "󰔷 "

[package]
  format = '[\[$symbol $version\]]($style)'
  style  = "bold peach"
  symbol = "󰏗"

[python]
  format = '[${symbol}(${version} )[(\($virtualenv\))](italic $style)]($style)'
  style  = "bold yellow"
  symbol = " "

[os.symbols]
  Arch        = " "
  Artix       = " "
  Debian      = " "
  EndeavourOS = " "
  Linux       = " "
  Manjaro     = " "
  Pop         = " "
  Raspbian    = " "
  Ubuntu      = " "
  Unknown     = " "
  Windows     = "󰍲 "

[rust]
  symbol = "󱘗 "

# Palette definitions
[palettes.catppuccin_frappe]
  rosewater = "#f2d5cf"
  flamingo  = "#eebebe"
  pink      = "#f4b8e4"
  mauve     = "#ca9ee6"
  red       = "#e78284"
  maroon    = "#ea999c"
  peach     = "#ef9f76"
  yellow    = "#e5c890"
  teal      = "#81c8be"
  green     = "#a6d189"
  sky       = "#99d1db"
  sapphire  = "#85c1dc"
  blue      = "#8caaee"
  lavender  = "#babbf1"
  text      = "#c6d0f5"
  subtext1  = "#b5bfe2"
  subtext0  = "#a5adce"
  overlay2  = "#949cbb"
  overlay1  = "#838ba7"
  overlay0  = "#737994"
  surface2  = "#626880"
  surface1  = "#51576d"
  surface0  = "#414559"
  base      = "#303446"
  mantle    = "#292c3c"
  crust     = "#232634"

[palettes.catppuccin_macchiato]
  rosewater = "#f4dbd6"
  flamingo  = "#f0c6c6"
  pink      = "#f5bde6"
  mauve     = "#c6a0f6"
  red       = "#ed8796"
  maroon    = "#ee99a0"
  peach     = "#f5a97f"
  yellow    = "#eed49f"
  green     = "#a6da95"
  teal      = "#8bd5ca"
  sky       = "#91d7e3"
  sapphire  = "#7dc4e4"
  blue      = "#8aadf4"
  lavender  = "#b7bdf8"
  text      = "#cad3f5"
  subtext1  = "#b8c0e0"
  subtext0  = "#a5adcb"
  overlay2  = "#939ab7"
  overlay1  = "#8087a2"
  overlay0  = "#6e738d"
  surface2  = "#5b6078"
  surface1  = "#494d64"
  surface0  = "#363a4f"
  base      = "#24273a"
  mantle    = "#1e2030"
  crust     = "#181926"

[palettes.catppuccin_mocha]
  rosewater = "#f5e0dc"
  flamingo  = "#f2cdcd"
  pink      = "#f5c2e7"
  mauve     = "#cba6f7"
  red       = "#f38ba8"
  maroon    = "#eba0ac"
  peach     = "#fab387"
  yellow    = "#f9e2af"
  green     = "#a6e3a1"
  teal      = "#94e2d5"
  sky       = "#89dceb"
  sapphire  = "#74c7ec"
  blue      = "#89b4fa"
  lavender  = "#b4befe"
  text      = "#cdd6f4"
  subtext1  = "#bac2de"
  subtext0  = "#a6adc8"
  overlay2  = "#9399b2"
  overlay1  = "#7f849c"
  overlay0  = "#6c7086"
  surface2  = "#585b70"
  surface1  = "#45475a"
  surface0  = "#313244"
  base      = "#1e1e2e"
  mantle    = "#181825"
  crust     = "#11111b"
