[pwsh.files]
  pwsh = '~\Documents\PowerShell'

[powershell.files]
  pwsh = '~\Documents\WindowsPowerShell'

[terminal.files]
  terminal = '~\scoop\apps\windows-terminal-preview\current\settings'

[sioyek.files]
  sioyek = '~\scoop\persist\sioyek'

[git.files]
  jj = '~\AppData\Roaming\jj'

[shell.files]
  bat  = '~\AppData\Roaming\bat'
  glow = { type = "symbolic", target = '~\AppData\Local\glow\Config' }

[bash.files."bash/bashrc"]
  append = """
# use builtin ssh on windows (not from git-for-windows)
export PATH="/c/Windows/System32/OpenSSH/":$PATH
"""
  target = '~\.bashrc'
  type = "template"

[media.files]
  mpv = '~\AppData\Roaming\mpv'
