[pwsh.files]
  pwsh = '~\Documents\PowerShell'

[powershell.files]
  pwsh = '~\Documents\WindowsPowerShell'

[terminal.files]
  terminal = '~\scoop\persist\windows-terminal-preview\settings'

[sioyek.files]
  sioyek = '~\scoop\persist\sioyek'

[git.files]
  jj = '~\AppData\Roaming\jj'

[shell.files]
  bat  = '~\AppData\Roaming\bat'
  glow = { type = "symbolic", target = '~\AppData\Local\glow\Config' }

[vscode.files]
  "vscode/keybindings-windows.json.temp" = '~\AppData\Roaming\Code\User\keybindings.json'
  "vscode/keybindings-linux.json.temp" = ""

[mpv.files]
  mpv = '~\AppData\Roaming\mpv'

[jpegview.files]
  jpegview = '~\scoop\persist\jpegview-fork'

[media]
  depends = ["jpegview", "mpv"]
