[pwsh.files]
  pwsh = '~\Documents\PowerShell'

[powershell.files]
  pwsh = '~\Documents\WindowsPowerShell'

[terminal.files]
  terminal = '~\scoop\persist\windows-terminal-preview\settings'

[sioyek.files]
  sioyek = '~\scoop\persist\sioyek'

[git.files]
  jj = '~\AppData\Roaming\jj'

[shell.files]
  bat  = '~\AppData\Roaming\bat'
  glow = { type = "symbolic", target = '~\AppData\Local\glow\Config' }

[bash.files."bash/bashrc"]
  append = """
# use builtin ssh on windows (not from git-for-windows)
export PATH="/c/Windows/System32/OpenSSH/":$PATH
"""
  target = '~\.bashrc'
  type = "template"

[vscode.files]
  "vscode/keybindings.json" = '~\AppData\Roaming\Code\User\keybindings.json'

[mpv.files]
  mpv = '~\AppData\Roaming\mpv'

[jpegview.files]
  jpegview = '~\scoop\persist\jpegview-fork'

[media]
  depends = ["jpegview", "mpv"]
