[pwsh.files]
  pwsh = '~\Documents\PowerShell'

[powershell.files]
  pwsh = '~\Documents\WindowsPowerShell'

[terminal.files]
  terminal             = '~\scoop\persist\windows-terminal-preview\settings'
  "terminal/Fragments" = '~\AppData\Local\Microsoft\Windows Terminal\Fragments'

[sioyek.files]
  sioyek = '~\AppData\Roaming\sioyek'

[git.files]
  jj = '~\AppData\Roaming\jj'

[shell.files]
  bat             = '~\scoop\persist\bat'
  glow            = { target = '~\AppData\Local\glow\Config', type = "symbolic" }
  "glow/glow.yml" = '~\AppData\Local\glow\Config\glow.yml'

[vscode.files]
  "vscode/keybindings-linux.json.temp"   = ""
  "vscode/keybindings-windows.json.temp" = '~\AppData\Roaming\Code\User\keybindings.json'
  "vscode/test_settings.json.template"   = '~\AppData\Roaming\Code\User\test_settings.json'

[npp.files]
  "notepad++/config.xml"    = { target = '~\Appdata\Roaming\Notepad++\config.xml', type = "template" }
  "notepad++/shortcuts.xml" = '~\AppData\Roaming\Notepad++\shortcuts.xml'
  "notepad++/themes/"       = '~\AppData\Roaming\Notepad++\themes\'

[vesktop.files]
  "vesktop/settings.json" = '~\scoop\persist\vesktop\Data\settings.json'
  "vesktop/settings/"     = { target = '~\scoop\persist\vesktop\Data\settings\', type = "symbolic" }
  "vesktop/themes/"       = { recurse = false, target = '~\scoop\persist\vesktop\Data\themes', type = "symbolic" }

[filepilot.files]
  filepilot = '~\AppData\Roaming\Voidstar\FilePilot'

[mpv.files]
  mpv = '~\AppData\Roaming\mpv'

[jpegview.files]
  "jpegview/JPEGView.ini" = '~\scoop\persist\jpegview-fork\JPEGView.ini'

[media.files]
  gallery-dl = '~\AppData\Roaming\gallery-dl'
