[sioyek.files]
  sioyek = "~/scoop/persist/sioyek"

[git.files]
  jj = "~/AppData/Roaming/jj"

[shell.files]
  bat  = { type = "symbolic", target = "~\\AppData\\Roaming\\bat", if = '(is_executable "bat")' }
  glow = { type = "symbolic", target = "~\\AppData\\Local\\glow\\Config", if = '(is_executable "glow")' }
