[sioyek.files]
  sioyek = "~/scoop/persist/sioyek"

[git.files]
  jj = "~/AppData/Roaming/jj"

[shell.files]
  glow    = { type = "symbolic", target = "~/.config/glow", if = '(is_executable "glow")' }
