#! /bin/sh

# bspwmrc configuration file
# Run on startup by session selector


# desktop tags
bspc monitor -d I II III IV V VI

# expansion helper
_() { bspc config "$@"; }

# mouse config
_ pointer_modifier          mod1
_ pointer_motion_interval   10

_ focus_follows_pointer     true
_ point_follows_focus       false


# border size and color
_ window_gap           20
_ bottom_padding       25       # padding for bar

_ border_width         2
_ focused_border_color "#98971a" # green
_ normal_border_color  "#3c3836" # grey

_ split_ratio          0.52


# other
_ gapless_monocle      true
_ single_monocle

bspc rule -a Xfce4-terminal:nnn desktop='^2'
bspc rule -a Xfce4-terminal:neovim desktop='^2'
bspc rule -a Xfce4-terminal:term1 desktop='^1'

#
# autostart
#

s() {pkill "$1"; { sleep 0.1; "$@"; } & }

s sxhkd
s compton
# s xfsettingd

# Window rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
