[helpers]

# special dotter settings
[settings]
default_target_type = "automatic"

[git.files]
gitconfig = "~/.config/git/config"
jj = {type="symbolic", target = "~/.config/jj", if = '(is_executable "jj")'}

[git.variables]
username = "jack-mil"
email = "62065280+jack-mil@users.noreply.github.com"

[shell.files]
ripgrep = { type = "symbolic", target = "~/.ripgreprc", if = '(is_executable "rg")'}

[bash]
depends = ["shell"]
files = { bashrc = "~/.bashrc", profile = "~/.profile" }

[nvim.files]
nvim = "~/.config/nvim"

[sioyek.files]
sioyek = "~/.config/sioyek"
