[helpers]

# special dotter settings
[settings]
  default_target_type = "automatic"

[ssh]
  # meta package for now

[git]
  depends = ["ssh", "shell"]
  [git.files]
    gitconfig = "~/.config/git/config"
    delta = "~/.config/delta"
    jj        = { type = "symbolic", target = "~/.config/jj", if = '(is_executable "jj")' }

  [git.variables]
    #optional: signing_key
    email    = "62065280+jack-mil@users.noreply.github.com"
    username = "jack-mil"

# other interactive stuff here? install utils?
[shell.files]
  glow     = { type = "symbolic", target = "~/.config/glow", if = '(is_executable "glow")' }
  ripgrep  = { type = "symbolic", target = "~/.ripgreprc", if = '(is_executable "rg")' }
  starship = { type = "symbolic", target = "~/.config", if = '(is_executable "starship")' }
  bat      = {type = "symbolic", target = "~/.config/bat", if = '(is_executable "bat")'}

[bash]
  depends = ["shell"]
  [bash.files]
    "bash/bash_aliases" = "~/.bash_aliases"
    "bash/bashrc"       = "~/.bashrc"

[nvim.files]
  nvim = "~/.config/nvim"

[sioyek.files]
  sioyek = "~/.config/sioyek"

[yazi.files]
  yazi = "~/.config/yazi"

# meta package(s) for now
[graphics]

[media]
  depends = ["graphics"]
