[helpers]

# special dotter settings
[settings]
  default_target_type = "automatic"

[ssh]
  # meta package for now

[git]
  depends = ["shell", "ssh"]
  [git.files]
    git = "~/.config/git"
    jj  = { type = "symbolic", target = "~/.config/jj", if = '(is_executable "jj")' }

  [git.variables]
    #optional: signing_key
    email    = "62065280+jack-mil@users.noreply.github.com"
    username = "jack-mil"

[scripts]
  depends = ["shell"]
  [scripts.files]
    scripts = "~/.local/bin"

# other interactive stuff here? install utils?
[shell.files]
  bat      = "~/.config/bat"
  bottom   = "~/.config/bottom"
  glow     = { type = "symbolic", target = "~/.config/glow" }
  starship = "~/.config/"

  ripgrep = "~/.config/"

[bash]
  depends = ["scripts", "shell"]
  [bash.files]
    "bash/bash_aliases" = "~/.bash_aliases"
    "bash/bashrc"       = "~/.bashrc"
    "bash/inputrc"      = "~/.inputrc"

[nvim.files]
  nvim = { target = "~/.config/nvim", recurse = false, type = "symbolic" }

[vscode.files]
  "vscode/keybindings.json" = "~/.config/Code/User/keybindings.json"

[sioyek.files]
  sioyek = "~/.config/sioyek"

[yazi.files]
  yazi = "~/.config/yazi"

# meta package(s) for now
[graphics]

[mpv.files]
  mpv = "~/.config/mpv"

[media]
  depends = ["mpv"]
