[helpers]

# special dotter settings
[settings]
  default_target_type = "automatic"

[ssh]
  # meta package for now

[kitty.files]
  kitty = { target = "~/.config/kitty", type = "symbolic" }

[git]
  depends = ["shell", "ssh"]
  [git.files]
    git = "~/.config/git"
    jj  = { if = '(is_executable "jj")', target = "~/.config/jj", type = "symbolic" }

  [git.variables]
    #optional: signing_key
    email    = "62065280+jack-mil@users.noreply.github.com"
    username = "jack-mil"

[scripts]
  depends = ["shell"]
  [scripts.files]
    scripts = "~/.local/bin"

# other interactive stuff here? install utils?
[shell.files]
  bat             = "~/.config/bat"
  bottom          = "~/.config/bottom"
  glow            = { target = "~/.config/glow", type = "symbolic" }
  "glow/glow.yml" = "~/.config/glow/glow.yml"
  ripgrep         = "~/.config/"
  starship        = "~/.config/"

[bash]
  depends = ["scripts", "shell"]
  [bash.files]
    "bash/bashrc"   = "~/.bashrc"
    "bash/bashrc.d" = "~/.config/bashrc.d"
    "bash/inputrc"  = "~/.inputrc"

[nvim.files]
  nvim = { recurse = false, target = "~/.config/nvim", type = "symbolic" }

[vscode.files]
  "vscode/keybindings-linux.json.temp" = "~/.config/Code/User/keybindings.json"

[sioyek.files]
  sioyek = "~/.config/sioyek"

[yazi.files]
  yazi = "~/.config/yazi"

[tmux.files]
  "tmux" = { recurse = false, target = "~/.config/tmux", type = "symbolic" }

# meta package(s) for now
[graphics]

[mpv.files]
  mpv = "~/.config/mpv"

[media]
  depends = ["mpv"]
  [media.files]
    aria2 = "~/.config/aria2"

[arch.files]
  "pacman/aura.toml"    = "~/.config/aura/config.toml"
  "pacman/makepkg.conf" = "~/.config/pacman/makepkg.conf"
