[formatting]
  align_entries     = true
  array_auto_expand = true
  column_width      = 60
  indent_entries    = true
  indent_tables     = true
  reorder_arrays    = true
  reorder_keys      = true
